language: python

jobs:
  include:
    - name: "Python 2.7 on Xenial Linux"
      python: 2.7           # this works for Linux but is ignored on macOS or Windows
      os: linux
      before_install:
        # NASA CDF
        - wget -r -l1 -np -nd https://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/ -A cdf*-dist-all.tar.gz
        - tar xf cdf*-dist-all.tar.gz
        - cd cdf*dist
        - make OS=linux ENV=gnu all
        - sudo make INSTALLDIR=/usr/local/cdf install
        - cd ..
        - pip install cycler==0.10.0
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      os: linux
      before_install:
        - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
        - pip3 install numpy==1.16.5
        - pip3 install scipy==1.2.1
        - pip3 install matplotlib==3.5.1
        - pip3 install importlib-metadata==4.12
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      os: linux
    - name: "Python 3.9 on Xenial Linux"
      python: 3.9           # this works for Linux but is ignored on macOS or Windows
      os: linux
    - name: "Python 3.10 on Ubuntu 20.04 Linux"
      python: 3.10          # this works for Linux but is ignored on macOS or Windows
      os: linux
      dist: focal
    - name: "Python 3.8.9 on macOS 12.4"
      os: osx
      osx_image: xcode13.4  # Python 3.7.4 running on macOS 12.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
    - name: "Python 3.9.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
  allow_failures:
    - os: windows
    - python: 2.7
    - python: 3.7
    - os: osx

cache: pip

addons:
  apt:
    packages:
        gcc
        gfortran
        libc-dev
        python-dev
        libncurses5-dev


install:
  - python3 setup.py install || python setup.py install

script:
  - python3 magpy/test/test_di.py || python magpy/test/test_di.py
  - python3 magpy/test/test_baseline.py || python magpy/test/test_baseline.py
